name: Nativescript CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Nativescript
        run: npm install -g nativescript

      - name: Install npm dependencies
        run: npm install

      - name: Set up android target
        run: ns platform add android

      - name: Build
        run: ns build android

      - uses: actions/upload-artifact@v2
        with:
          name: Vueddit
          path: ${{ github.workspace }}/platforms/android/app/build/outputs/apk/debug/app-debug.apk
